# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  j1_left:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j1_right:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j2_left:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j2_right:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j3_left:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j3_right:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j4_left:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j4_right:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j5_left:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j5_right:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j6_left:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0
  j6_right:
    has_velocity_limits: true
    max_velocity: 6.283185308
    has_acceleration_limits: false
    max_acceleration: 0