# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: home_left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - j1_left
    - j2_left
    - j3_left
    - j4_left
    - j5_left
    - j6_left_a
    - j6_left_b
    - j1_right
    - j2_right
    - j3_right
    - j4_right
    - j5_right
    - j6_right_a
    - j6_right_b
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: amber_leftarm
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j1_left
      - j2_left
      - j3_left
      - j4_left
      - j5_left
  - name: amber_lefthand
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    parallel: true
    joints:
      - j6_left_a
      - j6_left_b
  - name: amber_rightarm
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j1_right
      - j2_right
      - j3_right
      - j4_right
      - j5_right
  - name: amber_righthand
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    parallel: true
    joints:
      - j6_right_a
      - j6_right_b
