#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from amber_ros_driver.amber_action_server_node import AmberActionServerNode

try:
    aas_node = AmberActionServerNode()
    aas_node.run()
except rospy.ROSInterruptException:
    pass
